name: CUDA Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            build-essential \
            cmake \
            git \
            wget

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.5'

      - name: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.19
          

      - name: Build CUDA Project
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      - uses: actions/upload-artifact@v3
        with:
          name: cuda-library
          path: build/lib/libNeuZephyr.so
